### ISSUE TITLE
Apply getGraphBbox and zoomToFit to a given list of nodes

### ISSUE THREAD

**Issue by ivanbenavidesvt** [vasturiano/force-graph#132]
I have a lot of nodes in the graph but I need to fit the zoom or center the graph to a specific list of selected nodes.

I suggest extending the utilities "getGraphBbox" and "zoomToFit" as follow (or similar):
```
getGraphBbox(nodeIds)
zoomToFit([ms], [px], [nodeIds])
```

Being "nodeIds" a list of "ids" that represent the nodes to apply the utilities.

**Comment by vasturiano** [comment]
Thanks @ivanbenavidesvt, it's an awesome idea.

I've implemented this in the latest version (`1.30.0`), but changed the syntax slightly in order to make the functionality more generic. Instead of a list `nodeIds` it accepts a node filter method, which lets you specify any node logic you'd like.

Let me know if it works out for you.
