### ISSUE TITLE
is it possible to set individual node charge strength or link force?

### ISSUE THREAD

**Issue by wunaidage** [vasturiano/force-graph#137]
I have some free flying nodes which are not connected to any other node. they are always very far from the main group and make the graph very small when I try to zoomToFIt. the main group is usually very crowded so I set a very strong charge strength: -128 and relatively low link strength: 0.3 to reduce the link/ node overlapping situation. 
I think it's the high charge strength that pushes the free fly nodes that far. 
So is it possible to set individual node force?

**Comment by vasturiano** [comment]
@wunaidage thanks for reaching out.

The `charge` force is a global type of force that does not change on an individual node pair basis. This is by design, you can read a bit more about it here: https://github.com/vasturiano/d3-force-3d#forceManyBody

Most certainly it's this strong repelling force that's pushing the disconnected nodes far away. I think there's multiple ways you can address this.
* Set a [maximum distance](https://github.com/vasturiano/d3-force-3d#forceManyBody) for the charge force to act. So it doesn't keep on repelling nodes beyond a certain point.
* Instead of using the charge force to separate clusters of nodes, you can use a [collision force](https://github.com/vasturiano/d3-force-3d#forceManyBody). That will allow to decrease the charge to normal levels.
* Increase the `d3VelocityDecay ` introducing more resistance in the medium, which prevents the nodes from sliding too far.
* Add a limitting (container like) force to prevent the nodes from moving past certain boundaries, for example with [d3ForceLimit](https://github.com/vasturiano/d3-force-limit).

**Comment by wunaidage** [comment]
Thank you Vasco! so I guess link force is also a global setting, right?

**Comment by vasturiano** [comment]
@wunaidage you can set the intensity of the link force individually per link: https://github.com/d3/d3-force#link_strength

**Comment by wunaidage** [comment]
so I have two array of links: weakLinks = [] and strongLinks = []
but when I try to set link force by
this.graph.d3Force('link', d3.forceLink(weakLink).strength(0.1));
this.graph.d3Force('link', d3.forceLink(strongLink).strength(0.7));
the later one always override to earlier number.

**Comment by vasturiano** [comment]
@wunaidage if all you want is to change some setting of the link force, you should not re-instantiate `d3.forceLink`. If you do so it will replace the previous link force every time. You should access and update the existing force, via `myGraph.d3Force('link')`.

So, instead of this: `this.graph.d3Force('link', d3.forceLink(links).strength(0.1));`
Just do this: `this.graph.d3Force('link').strength(0.1);`

**Comment by wunaidage** [comment]
Thank you Vasco! Finally I figured out how to install the strength individually.
```
this.graph.d3Force('link', d3.forceLink().links(links).strength((link: ForceGraphLink) => {
      if (this.strongForceLinks.find(theLink => theLink.id === link.id)) {
        return STRONG_LINK_STRENGTH;
      }
      if (this.mediumForceLinks.find(theLink => theLink.id === link.id)) {
        return MEDIUM_LINK_STRENGTH;
      }
      if (this.weakForceLinks.find(theLink => theLink.id === link.id)) {
        return WEAK_LINK_STRENGTH;
      }
    }));
```
