### ISSUE TITLE
update dependency for security reasons

### ISSUE THREAD

**Issue by FrissAnalytics** [vasturiano/force-graph#145]
Hi Vasco,

hope you are doing well! 

FYI: during a security scan we found a potential issue that was tracked to `tinycolor2` that is used in `canvas-color-tracker` and of course `force-graph`. 

This was assessed as a medium security risk, which fortunately was very easy to mitigate. Some other folks found this too and by the time we found out there was already an update to the git repo, but not yet to npm.

See [here](https://github.com/bgrins/TinyColor/pull/205#issuecomment-682579554) for more details in case you wonder what security issues it refers to. 

In short, it turned out that tinycolor2 in its tests relied on a particular jQuery version that gets flagged as a security risk. The author removed this dependency and submitted a new version to npm just this week.

Hence, only a version bump of tinycolor is needed. Would it be possible to make this update?

Anyway, just a suggestion of course! Again thanks for all your amazing work!

kind regards, Herman

**Comment by vasturiano** [comment]
Hi Herman,

Thanks for the heads up on this. I've bumped the deps on both packages and published new versions.
You can see the bump in `tinycolor2` here:
https://github.com/vasturiano/force-graph/commit/bcb5e157e1f73d84568a34debcc9e778c58db948#diff-8ee2343978836a779dc9f8d6b794c3b2R2862

Just as a side note, since it was only a patch upgrade, you actually didn't need to wait for me to do this upgrade. The chain of dependencies generally include a `^`, meaning any minor/patch increases of the same major version will be satisfied. So you can just upgrade your lock file (`yarn upgrade` f.e.) and you'll get the new version of `tinycolor2` in your app.
But I appreciate you mentioning, that prompted me to resolve the vulnerability in that module.  😄

**Comment by FrissAnalytics** [comment]
thanks, much appreciated!
