### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by sholtodouglas** [vasturiano/force-graph#16]
Hi, really nice work! This makes dealing with d3 significantly easier! I was wondering what the best way to implement a simple search that highlights desired nodes by name would be? E.g, how could I modify the lower level parts of your code to include search functions like this one - https://bl.ocks.org/jrladd/raw/c76799aa63efd7176bd9006f403e854d/

**Comment by vasturiano** [comment]
Hi @sholtodouglas, thanks for reaching out. I can imagine you could have a highlighting mechanism similar to this example: https://vasturiano.github.io/force-graph/example/highlight/, with the difference that the data filtering logic would be derived from a search input field instead of the mouse hover event.

Let me know if you can get it to work!

**Comment by sholtodouglas** [comment]
Thanks Vasturiano, I'll give it a shot :)
