### ISSUE TITLE
Touch friendly option for on{Node,Link,Background}RightClick

### ISSUE THREAD

**Issue by xlfe** [vasturiano/force-graph#208]
**Is your feature request related to a problem? Please describe.**

We're building a mobile-first Single Page App and we'd like to add a context menu to our force-graph visualisation (on nodes, links and background). For devices with a mouse, right click is perfect, but on touch devices, there is no equivalent. We need to support all functionality on touchscreen so we cannot just add a right click context menu that is not accessible on mobile/touch devices.

**Describe the solution you'd like**

It would be great if you would add an option `longPressRightClickThreshold` which -when set- would convert any click & hold event longer than the threshold (eg mousedown 4s later mouseup) into the appropriate rightclick event.

**Describe alternatives you've considered**

I cannot write my own, because the mousedown/mouseup events are not exposed by force-graph.

**Comment by vasturiano** [comment]
@xlfe thanks for reaching out.

As described in the docs the pointer events are included (as 2nd argument) in the "onClick" event methods: https://github.com/vasturiano/force-graph#interaction

Is this sufficient for you to add your own custom interaction combinations?

**Comment by xlfe** [comment]
Hmm. I can't see how? 

Doing a console log of the event object in both onNodeClick and onNodeRightClick shows it only firing once for each click (even a click+hold) - the only pointerevent I get is "pointerup"

So it's not passing through "pointerdown"

I'd be happy to put together a PR for your consideration?

**Comment by vasturiano** [comment]
@xlfe if the only thing you're missing is the original `pointerdown` event, we could think of including that in the argument list of the methods (f.e. `onNodeClick(node, pointerupEvent, pointerDownEvent)`). You could then subtract the `timeStamp` attributes in the events to determine if a certain amount of time has passed. Would that be sufficient to solve your use case?

What I would avoid is to surface a `onNodePointerDown` type of functionality, because of the fact that at that point in time it's not yet clear whether the interaction is a node/canvas drag, or an element click/touch. That distinction only becomes available at the time of `pointerup`.

**Comment by xlfe** [comment]
@vasturiano yes I think adding the pointerDownEvent would be sufficient - then as you suggest subtracting the two timestamps to check the threshold for a long-press detection.

Agree with avoiding the onNodePointerDown - you only know whether its longpress on the pointerup event!

Your suggestion sounds great - thanks - if there's anything I can do let me know

**Comment by vasturiano** [comment]
@xlfe ok, in the latest version (`1.42.0`) you'll find that all the click related callback methods have an additional argument which is the original `pointerdown` event.
Let me know if this feature fully solves your issue. 👍
