### ISSUE TITLE
How can the code in ‘nodeCanvasObject()’ be written to become a node hovering style like sigma.js

### ISSUE THREAD

**Issue by FightingQueen** [vasturiano/force-graph#231]
The node is surrounded by a black background, so you can see which node the name belongs to.
At the same time, the background level is the highest and is not covered by other nodes.
How do I write the canvas code in nodeCanvasObject(node,ctx)  to meet the style shown in the following picture?
I don't know much about canvas. Please give a specific code example. Thank you

![example](https://user-images.githubusercontent.com/29089344/135403709-2737d742-5cff-4ee6-a72c-efe658fc0843.jpg)

**Comment by FightingQueen** [comment]
I'm sorry, you may think the tone was stiff in the past, but I meant to ask you some questions humbly. Please don't mind

**Comment by vasturiano** [comment]
@FightingQueen thanks for reaching out.

This seems to be more a question about [Canvas](https://www.w3schools.com/html/html5_canvas.asp) development rather than this module in specific. As such, you will probably get a more helpful answer by posting in StackOverflow, or a more Canvas oriented forum.
