### ISSUE TITLE
Node size issue

### ISSUE THREAD

**Issue by chinjen** [vasturiano/force-graph#237]
**Describe the bug**
I am trying to set different size at each node. In the end I use nodeVal() to solve.
The issue is that when I set big size and the node actually is as big as I set but the node will cover the link which other node comes from. The expectation that the link will shoot out along with the big size node edge.

**Expected behavior**
The expectation that the link will shoot out along with the big size node edge.

Screenshot is as below.

Before:
![image](https://user-images.githubusercontent.com/39974700/141234857-a679faa8-b388-4f79-8ef0-dbc28c746d9c.png)

After:
![image](https://user-images.githubusercontent.com/39974700/141234753-c1f6b293-c0d9-4f7c-904b-ae1e684d11f4.png)

Code is here
I replace NodeVal() with NodeRelSize()
![image](https://user-images.githubusercontent.com/39974700/141234973-2f24bf1a-89d1-4a50-8590-c88c26d77d99.png)

**Comment by vasturiano** [comment]
@chinjen thanks for reaching out. 

The links are rendered behind the nodes, this is intentional as it yields a less cluttered view of the graph. However, you can still visually surface the links to some extent by setting a semi-transparent color in the nodes that allows for some see-through. For example, you can set your node colors like this:
```js
.nodeColor(node => 'rgba(255,0,0,0.6)')
```

**Comment by chinjen** [comment]
@vasturiano Thank you very much for your clarification.
I will try to change node color as your suggestion. Thank you so much.
