### ISSUE TITLE
Not All Nodes Are Clickable (On Brave Browser, When Deployed To Github Pages or Netlify)

### ISSUE THREAD

**Issue by manunamz** [vasturiano/force-graph#247]
**Describe the bug**
In Brave Browser, some nodes are clickable and some are not if graph is deployed to github pages or netlify (yet works fine on my own machine). This behavior occurs regardless of default or dag-mode.

**To Reproduce**
I found this bug working on my site with github pages and netlify, but this behavior also occurs in the [example site](https://vasturiano.github.io/force-graph/example/directional-links-particles/) in Brave Browser. 

A quick mouse hover will show a large number of nodes do not react to cursor events (hover/click).

**Expected behavior**
Reactive nodes to be clickable, hoverable, etc.

**~~Screenshots~~ Live Examples**
See above example site above.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser [e.g. chrome, safari]: Brave Browser
 - Version [e.g. 22]: v1.22.71 (Brave)

**Smartphone (please complete the following information):**
- N/A

**Additional context**
Otherwise works exquisitely on other browsers and devices (tested desktop, mobile, and tablet). Well done, sir. 👍

**Comment by vasturiano** [comment]
@manunamz thanks for reaching out. 

This is actually a known issue with Brave due to its security feature of fingerprint logging, it meddles with the exact colors returned by canvas' `getImageData`. Which in turn causes erratic hover behaviour.
Some more details in this other issue: https://github.com/vasturiano/force-graph/issues/177

Only known workaround is to disable the "fingerprinting protections" feature in the Brave browser settings. 🤷

**Comment by manunamz** [comment]
Oh! 👍 Got it -- thanks for taking the time to write that up. 🙏

**Comment by exrhizo** [comment]
I forked one of the libraries to fix this
https://github.com/coordinape/coordinape/tree/main/canvas-color-tracker
