### ISSUE TITLE
How to implement incremental graphData update on zoom and pan?

### ISSUE THREAD

**Issue by ArtVolchara** [vasturiano/force-graph#343]
Hello @vasturiano, firstly i would like to thank you for the nice library.
While implementing nodes and links update on zoom and pan i faced an infinate loop problem. It seams onZoom and OnZoomEnd also invoked on graphData update (https://github.com/vasturiano/react-force-graph/issues/345).  How many times it happens after graphData is updated with not empty data? I have a huge graph on server and i want to load on zoom and pan a certain part of it, which size depends on k, x, y. How would you recommend to do it on my place?
Hope to get your answer.

**Comment by vasturiano** [comment]
@ArtVolchara thanks for reaching out.

What you're describing happens if the graph data is updated and the canvas pan/zoom has yet not been touched by the user. Because the optimal zoom level is attempted to be set when the graph loads new data, so that all the nodes are within view. After the user performs any navigation operation, this automatic re-scaling is abandoned as the user is assumed to be in control from that point on.

This is why you experience the trigger of the `onZoom` and `onZoomEnd` methods after data refresh.

**Comment by ArtVolchara** [comment]
> @ArtVolchara thanks for reaching out.
> 
> What you're describing happens if the graph data is updated and the canvas pan/zoom has yet not been touched by the user. Because the optimal zoom level is attempted to be set when the graph loads new data, so that all the nodes are within view. After the user performs any navigation operation, this automatic re-scaling is abandoned as the user is assumed to be in control from that point on.
> 
> This is why you experience the trigger of the `onZoom` and `onZoomEnd` methods after data refresh.

So if I emulate user touch - invoke zoom let's say on mount, future graph.graphData({nodes: [...], links: [...]}) won't trigger zoomEnd?

**Comment by ArtVolchara** [comment]
It seams like my problem is gone. Thank you very much for the library!
