### ISSUE TITLE
Get API for simulation.alpha as .d3Alpha

### ISSUE THREAD

**Issue by Exymat** [vasturiano/force-graph#369]
While we have access to AlphaDecay and we are provided with cooldownTicks (when setted) and cooldownTime (by default 15000ms) to guess more or less how long we are expected the simulation to last for before the engine stops, both of these gives approximation that are not controlled by AlphaDecay, which is the real metric that triggers engine to stop when AlphaMin gets to it's value (default 0)
In this case, calculating a progress bar (which is what I'm trying to do) gets challenging as we are always basing ourselves on an estimate with either cooldownTicks or cooldownTime , since the simulation engine might stop well before we reach the target.
Having an access to the simulation starting alpha and current tick alpha (even though we could get the same result by using AlphaDecay on onTick by substracting it to the starting alpha) would provide a nice metric to know how long we can expect the simulation to be running.

**Comment by vasturiano** [comment]
@Exymat thanks for reaching out.

You make a compelling point for having access to the simulation alpha, which hadn't occurred to me before.
Also, it seems that what would be the most useful for your progress bar use case is to get notified of when the alpha changes, not the ability to get it from the simulation otherwise you need to keep polling for it.

So, we could provide it as an argument on the `onEngineTick` method. However, there's even an easier way to get it, albeit not immediately apparent. You can just make a "dummy" force whose only purpose is to extract the alpha, that essentially gets invoked every time the engine ticks.

It would be something as simple as this:
```js
.d3Force('getAlpha', alpha => console.log(alpha))
```

Let me know if this works for you.

**Comment by Exymat** [comment]
That does indeed work, I've never thought of using a dummy this way. That's a smart trick 😄 I do agree on your point about the progress bar, I was trying to figure something out with what was accessible with the current API reference.
Which now makes me wish we had an API to get notified of when the alpha changes, but as far as I am concerned, for the use case I have, what you've provided is a great all rounder, so I'll mark this as closed. Thanks 👍

**Comment by vasturiano** [comment]
@Exymat great, glad to know it works. For the sake of API simplicity I won't include the alpha in the `onEngineTick`method just yet. If more need arises from other users to have this then we can always reconsider it then. 👍
