### ISSUE TITLE
Add div in side the node canvas

### ISSUE THREAD

**Issue by somu2324** [vasturiano/force-graph#50]
**Is your feature request related to a problem? Please describe.**
Is it possible if I to use div as a Node. By default node are canvas but I want to use div as a node. 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vasturiano** [comment]
@somu2324 you cannot directly use a `div` or any type of DOM objects as nodes. They need to be created as Canvas drawing instructions using `nodeCanvasObject(...)`. This is in part for performance reasons so that the browser doesn't get overloaded with two many nodes in the document.

However, you could try converting your DOM elements to canvas images, so that you can draw them that way, using something like [html2canvas](http://html2canvas.hertzen.com/).

**Comment by somu2324** [comment]
Thanks @vasturiano. 
one more thing. Do we have any callback method through which I can capture x and y position of mouse respect to node. 
something link onNodeMouseMove(event) which may give event.x and event.y with respect to node center position.

**Comment by vasturiano** [comment]
@somu2324 you can derive that information using various sources:
* Attaching mouseMove events to your DOM element will give you mouse movement coordinates
* Each of your node objects will have `{ x, y }` coordinates indicating their current position on the canvas
* By calling the getters `.centerAt()` and `.zoom()` you can extract the current pan/zoom settings of the canvas, if the user has interacted with it.
