### ISSUE TITLE
Node hovering sensitivity

### ISSUE THREAD

**Issue by soccerdroid** [vasturiano/force-graph#51]
Hello again!
I was wondering if there is a parameter I can access to in order to configure the sensitivity area of a node when hovering. I want to do this because currently, I am drawing the nodes dynamically, and their size depends on a given feature of a node. I also add labels to the nodes, which are centered. When trying to drag or click the node, I can only do this if I place the cursor over the label, this is, at the center of the node.

**Comment by somu2324** [comment]
@vasturiano 
I am also have same kind of issue.  I've created the custom node. In the custom node is created few rectangle. I want to know on mouse move over node, my mouse pointer is at which rectangle.  
if somehow I can get x and y location of mouse pointer over node then it can help me. 
please let me know how can I get these information.

**Comment by vasturiano** [comment]
@soccerdroid, @somu2324 setting `nodeRelSize` and/or `nodeValue` will let you control the mouse trap area of a node when drawing custom nodes using `nodeCanvasObj`.

If you wish to see how big those trap areas are, you can temporarily set `.nodeCanvasObjectMode(() => before`, so that the default circle node is also drawn.

**Comment by soccerdroid** [comment]
hi @vasturiano ! Thank you for your answer, I haven't tried it yet but I will. Here is the [GSoC project](http://ec2-3-80-82-250.compute-1.amazonaws.com/) in which I worked with force-graph. Nice library! Thank you
