### ISSUE TITLE
Draw Sine wave as link and let particles move along the Sine wave link 

### ISSUE THREAD

**Issue by wunaidage** [vasturiano/force-graph#60]
I am able to draw sine wave as link with linkCanvasObject. but the particles still move in a straight line. Is any way to draw custom link and let particles move along the link?

**Comment by vasturiano** [comment]
@wunaidage that is not currently possible, because the component is not aware of the geometric logic used for the path drawing in the custom `linkCanvasObject` method.

But, you can always draw the particles yourself in the same method. That method will be called at every render frame so if you iteratively change the position of the particles along your chosen path, it should give you the effect you're looking for.

**Comment by wunaidage** [comment]
@vasturiano that's a good idea.
