### ISSUE TITLE
Increase link distance and dragend sticky method

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#66]
way to increase link distance(available only in force).
 Also after dragend event i want node to be fixed at dragged position, but there is no sample for dragend method.

**Comment by ravik3592** [comment]
Graph.d3Force('link').distance(link => this.nodeDistance);
This helped me solve link distance,
can you suggest way to make nodes stick to dragged position ondragend event

**Comment by vasturiano** [comment]
@ravik3592 you could fix the nodes in the `onNodeDragEnd` handler. Something like:
```
.onNodeDragEnd(node => {
  node.fx = node.x;
  node.fy = node.y;
})
```

**Comment by ravik3592** [comment]
It worked thanks. but however, if i do this, on drag other nodes are running out of screen

**Comment by vasturiano** [comment]
@ravik3592 what do you mean exactly? Could you make a [CodePen](https://codepen.io/) showing the effect you're describing?

**Comment by ravik3592** [comment]
https://codepen.io/ravi3592/pen/RwwGNrm

Find the 30 sec video in the below link, which explains the problem im facing currently
https://www.screencast.com/t/dXXefQ1LocTv

**Comment by vasturiano** [comment]
I see. That's because of the [centering force](https://github.com/d3/d3-force#centering), that is trying to bring the graph center of gravity to the middle of the canvas. That's why fixing some nodes will affect the other ones.

You can try deactivating the center force like this:
```
myGraph.d3Force('center', null);
```

The disadvantage may be that your graph can drift away from the center of the canvas, so you can also try deactivating the center force only when you start fixing nodes and not before.

**Comment by ravik3592** [comment]
Yes it worked. Thanks
