### ISSUE TITLE
Default contextmenu during onBackgroundRightClick

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#67]
I have custom contextmenu on noderightclick but i want to preserve the default contextmenu during onBackgroundRightClick. 
Is there any option to make this work.

**Comment by vasturiano** [comment]
@ravik3592 if you specify a right-click method, the default contextmenu behavior is disabled since it's assumed you wish to handle those interactions in a custom manner.
You could however still manually trigger a [contextmenu event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) on your method handler if you wish.

**Comment by ravik3592** [comment]
Thanks it worked
