### ISSUE TITLE
Plese check link.source and link.target before using them.

### ISSUE THREAD

**Issue by vadim-ivlev** [vasturiano/force-graph#81]
**Thanks a lot for a great library!**

Could you please add a line 

    if (!start || !end) return;

before lines 

    if (!start.hasOwnProperty('x') || !end.hasOwnProperty('x')) return; // skip invalid link

in functions `paintLinks()`, `calcLinkControlPoints()`, `paintArrows()`, `paintPhotons()` in 
`src/canvas-force-graph.js`  file ?

Sometimes after calling `.linkSource(...), .linkTarget(..)` start and end variables in theese functions become undefined, and subsequent code rises an exeption.

**Comment by vasturiano** [comment]
@vadim-ivlev thanks for reaching out. I would prefer not to do that as it would silently cause for invalid links to be ignored. I think it's better to error to alert the consumer application that some of the input links are erroneous and need be debugged. Otherwise the results will be surprising as some of the links will be mysteriously missing.

**Comment by vadim-ivlev** [comment]
Hi Vasco,

That's reasonable, thanks for your reply.

Happy New Year!
Vadim


пн, 30 дек. 2019 г. в 02:28, Vasco Asturiano <notifications@github.com>:
