### ISSUE TITLE
Change node colors without reloading graph

### ISSUE THREAD

**Issue by pournaki** [vasturiano/force-graph#95]
I want to create a funtion to recolor nodes using nodeAutoColorBy({arg}), where {arg} is the value of a selectbox (and a key of the node dict). However, when I run Graph.nodeAutoColorBy({arg}), the nodes all move a little bit, but their color does not change. Is there a way to toggle the nodeAutoColorBy function?

Maybe, to be a bit clearer, here's the detailed idea:

First, I want all nodes to be black by default, so I use:
```
Graph.nodeColor(() => '#000')
```
Then, I want them to change to a color assigned to them by the AutoColorBy function (in this case the node id), so I use (on click):
```
Graph.nodeAutoColorBy('id')
```
which does not work. I am probably doing something wrong, so I am wondering about the proper way to do this. 

Thanks a lot!

**Comment by vasturiano** [comment]
@pournaki thanks for reaching out.

`nodeAutoColorBy` only affects nodes that don't already have a color assigned. Since you've previously assigned a color to nodes using `nodeColor`, the automatic `nodeAutoColorBy` will have no effect.

I'd recommend implementing your own logic for node colors using `nodeColor(node => ...)`. `nodeAutoColorBy` is only meant as a simple convenience use case, not for more sophisticated logic, nor to use in combination with `nodeColor`.

**Comment by pournaki** [comment]
@vasturiano thanks for your quick reply! This is what I'll do then 👍
